security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Admin
                property: email 

    password_hashers:
        App\Entity\Admin:
            algorithm: auto

    firewalls:

        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^(/(fr|en|es))?/api
            stateless: true
            jwt: ~ 

        main:
            pattern: ^/(?!api)
            provider: app_user_provider
            custom_authenticator: App\Security\AdminAuthenticator
            logout:
                path: app_logout
                target: /login

    

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        


        


    access_control:
        # - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^(/(fr|en|es))?/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }


        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/(fr|en|es)(/|$), roles: PUBLIC_ACCESS }

        - { path: ^/admin, roles: ROLE_USER }
        - { path: ^/(fr|en|es)/([a-z0-9-]+)$, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10

