services:
  php-fpm:
    build:
      context: "./docker/php/"
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - "./:/var/www/app:rw"
      - "~/.cache/composer:/var/www/.composer:rw"
    container_name: ${CONTAINER_NAME}_php-fpm
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=app"
      XDEBUG_CONFIG: "remote_host=172.18.0.1 remote_enable=1"
      BLACKFIRE_SERVER_ID: ~
      BLACKFIRE_SERVER_TOKEN: ~
      APP_ENV: ${APP_ENV}
    working_dir: /var/www/app
    links:
      - database
      - maildev
  apache:
    build:
      context: "./docker/apache/"
    links:
      - php-fpm
    depends_on:
      - php-fpm
      - database
    ports:
      - "${APACHE_PORT}:80"
    volumes:
      - "./:/var/www/app:rw"
      - "./docker/apache/logs/:/var/log/apache2"
    container_name: ${CONTAINER_NAME}_apache
  adminer:
    image: adminer
    ports:
      - "${ADMINER_PORT}:8080"
    container_name: ${CONTAINER_NAME}_adminer

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "${POSTGRES_DB:-app}",
          "-U",
          "${POSTGRES_USER:-app}",
        ]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      JWT_KEY: "!ChangeThisMercureKey!"
      ALLOW_ANONYMOUS: "1"
      CORS_ALLOWED_ORIGINS: "*"
      PUBLISH_ALLOWED_ORIGINS: "http://localhost:8001"
    volumes:
      - mercure_data:/data
    ports:
      - "3000:80"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: ${CONTAINER_NAME}_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  mercure_data:
  database_data:
  esdata:
