controllers:
  resource: ../src/Controller/
  type: attribute
  prefix: /{_locale}
  requirements:
    _locale: fr|en|es
  defaults:
    _locale: fr

app_login:
  path: /{_locale}/login
  controller: App\Controller\SecurityController::login
  requirements:
    _locale: fr|en|es
  defaults:
    _locale: fr

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

app_register:
  path: /{_locale}/register
  controller: App\Controller\RegisterController::register
  requirements:
    _locale: fr|en|es
  defaults:
    _locale: fr


app_blog:
  path: /{_locale}
  controller: App\Controller\BlogController::show
  requirements:
    _locale: fr|en|es
  defaults:
    _locale: fr

app_profil:
  path: /{_locale}/{slug}
  controller: App\Controller\ProfilController::show
  requirements:
    _locale: fr|en|es
    slug: (?!favicon\.ico).+
    

redirect_to_locale:
  path: /{slug}
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: app_profil
    _locale: fr
  requirements:
    slug: .+
  methods: [GET]
  options:
    expose: true

