name: Symfony CI

on:
  push:
    branches: [main] #Action quand je push sur main 
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: app
          POSTGRES_USER: app
          POSTGRES_PASSWORD: app
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo, pdo_pgsql
          ini-values: post_max_size=256M, max_execution_time=300
          coverage: none

      - name: Install composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader --no-interaction

      - name: Install PHP CodeSniffer
        run: composer global require "squizlabs/php_codesniffer=*"
      
      - name: Run PHP CodeSniffer
        run: ~/.composer/vendor/bin/phpcs --standard=PSR12 src

      - name: Install PHPStan
        run: composer global require phpstan/phpstan

      - name: Run PHPStan (level 5)
        run: ~/.composer/vendor/bin/phpstan analyse src --level=5


  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t symfony-app .

      - name: List Docker images
        run: docker images
